[medic]
textfile=c:\medic\medic.uk
workdir=c:\medic
dicomserver=1
testdicom=0
applicationname=Medic DICOM import
host=localhost
port=8090
autoimport=1
useblockingsocket=1
importdir=c:\medic\export
[autoimportmailboxes]
nboxes=3
box1=MEDIC,c:\medic\mailbox
box2=DICOMFILE,c:\medic\dicomfiles
box3=DICOM,c:\medic\dicomin
[dicom]
AEtitle=MEDIC2000_SCP
maxPDUlength=16384
port=4030
dicomdir=c:\medic\dicomin
[dicomnodes]
;MERGE=172.24.38.28,104,MERGE_STORE_SCP
[dataset]
datadir=C:\medic\data
singledatadir=1
